import Head from "next/head";

import StaticVr from "../components/StaticVr";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ozak Gyo Örnek Daire</title>
        <meta name='description' content='Generated by Morph' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <StaticVr />
    </>
  );
}
